-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        rounding = 10,
    },
    general = {
        allow_tearing = false,
        col = {
            active_border = {
                colors = {"rgba(cba6f7ff)", "rgba(cba6f7ff)"},
                angle = 45,
            },
        },
        layout = "dwindle",
        snap = {
            enabled = false,
        },
    },
    misc = {
        disable_hyprland_logo = false,
        disable_splash_rendering = true,
        force_default_wallpaper = -1,
    },
})

-- Bezier curves
hl.curve("almostLinear", { type = "bezier", points = { {0.5, 0.5}, {0.75, 1.0} } })

-- Animations
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
})

-- Keybinds
hl.unbind("SUPER + R")
hl.bind("SUPER + D", hl.dsp.exec_cmd("rofi -show drun"))
hl.unbind("SUPER + SHIFT + M")
hl.bind("SUPER + SHIFT + M", hl.dsp.exec_cmd("hyprlock"))
hl.unbind("SUPER + P")
hl.bind("SUPER + space", hl.dsp.window.pseudo())
hl.unbind("Print")
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m region"))
hl.unbind("SUPER + mouse:272")
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), {
    mouse = true,
})
hl.unbind("SUPER + mouse:273")
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), {
    mouse = true,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar -c ~/.config/waybar/hypr/config.jsonc -s ~/.config/waybar/hypr/style.css")
    hl.exec_cmd("hyprpaper")
end)
