-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        rounding = 0,
    },
    general = {
        allow_tearing = false,
        col = {
            active_border = {
                colors = {"rgba(cba6f7ff)", "rgba(cba6f7ff)"},
                angle = 45,
            },
        },
    },
    misc = {
        disable_splash_rendering = true,
    },
})

-- Bezier curves
hl.curve("almostLinear", { type = "bezier", points = { {0.5, 0.5}, {0.75, 1.0} } })

-- Animations
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
})

-- Keybinds
hl.unbind("SUPER + R")
hl.bind("SUPER + D", hl.dsp.exec_cmd("rofi -show drun"))

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
end)
